package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"net/netip"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/netbirdio/netbird/client/embed"

	"github.com/xrey167/meshmcp/air"
	"github.com/xrey167/meshmcp/policy"
	"github.com/xrey167/meshmcp/session"
)

// Air Handoff is the Continuity seam between agents and devices. It moves an
// inert, expiring Context Capsule to an exact WireGuard key, persists it under
// the verified source identity, and requires an explicit local accept before a
// receiver-selected governed tool can continue the work in a fresh agent.
// It deliberately does not transfer a live session or its CreatorKey.
func cmdAirHandoff(args []string) error {
	if len(args) == 0 {
		return airHandoffUsage()
	}
	switch args[0] {
	case "offer", "send":
		return cmdAirHandoffOffer(args[1:])
	case "receive", "recv":
		return cmdAirHandoffReceive(args[1:])
	case "list", "inbox":
		return cmdAirHandoffList(args[1:])
	case "show":
		return cmdAirHandoffShow(args[1:])
	case "accept":
		return cmdAirHandoffTransition(args[1:], air.HandoffAccepted)
	case "rearm":
		return cmdAirHandoffRearm(args[1:])
	case "archive", "prune":
		return cmdAirHandoffArchive(args[1:])
	case "decline", "reject":
		return cmdAirHandoffTransition(args[1:], air.HandoffDeclined)
	case "continue":
		return cmdAirHandoffContinue(args[1:])
	case "help", "-h", "--help":
		return airHandoffUsage()
	default:
		return fmt.Errorf("air handoff: unknown subcommand %q (want offer | receive | list | show | accept | decline | continue | rearm | archive)", args[0])
	}
}

func airHandoffUsage() error {
	fmt.Fprintln(os.Stderr, bold("meshmcp air handoff")+dim(" — Continue on… for governed agents"))
	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "  "+bold("handoff offer")+"    --target-key <key> --work task:id --goal <text> <peer-ip:port>")
	fmt.Fprintln(os.Stderr, "  "+bold("handoff receive")+"  --inbox <dir> --allow <identity> [--port 9140]")
	fmt.Fprintln(os.Stderr, "  "+bold("handoff list")+"     --inbox <dir> [--state <state>] [--json]")
	fmt.Fprintln(os.Stderr, "  "+bold("handoff show")+"     --inbox <dir> <id>")
	fmt.Fprintln(os.Stderr, "  "+bold("handoff accept")+"   --inbox <dir> <id>")
	fmt.Fprintln(os.Stderr, "  "+bold("handoff decline")+"  --inbox <dir> <id>")
	fmt.Fprintln(os.Stderr, "  "+bold("handoff continue")+" --inbox <dir> --agent-key <key> --tool <destination-tool> <id> <agent-ip:port>")
	fmt.Fprintln(os.Stderr, "  "+bold("handoff rearm")+"    --inbox <dir> --note <receipt-check> <id>  "+dim("retry an unknown dispatch explicitly"))
	fmt.Fprintln(os.Stderr, "  "+bold("handoff archive")+"  --inbox <dir> [--older-than 24h]  "+dim("retain old terminal/expired-unknown receipts outside active quota"))
	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, dim("Capsules are data, not authority: the destination chooses the tool and its normal policy still applies."))
	return nil
}

func cmdAirHandoffOffer(args []string) error {
	fs := flag.NewFlagSet("air handoff offer", flag.ExitOnError)
	o := meshFlags(fs)
	targetKey := fs.String("target-key", "", "exact destination WireGuard public key (required; pubkey: prefix accepted)")
	workRaw := fs.String("work", "", "work reference: agent:<id> | session:<id> | task:<id> | workflow:<id> (required)")
	goal := fs.String("goal", "", "what the destination should continue (required; inert context, never auto-executed)")
	summary := fs.String("summary", "", "short context summary")
	cursorPath := fs.String("cursor", "", "JSON cursor/context file; use - for stdin")
	sensitivity := fs.String("sensitivity", air.SensitivityStandard, "low | standard | sensitive | restricted")
	ttl := fs.Duration("ttl", 30*time.Minute, "offer lifetime (maximum 24h)")
	networkTimeout := fs.Duration("timeout", 2*time.Minute, "maximum time to wait for a destination ACK")
	id := fs.String("id", "", "optional 32-hex correlation and offer-replay id (generated by default)")
	asJSON := fs.Bool("json", false, "print the full sent offer as JSON (may contain private context)")
	artifacts := multiFlag{}
	memoryRefs := multiFlag{}
	secretRefs := multiFlag{}
	labels := multiFlag{}
	fs.Var(&artifacts, "artifact", "CAS artifact reference name=sha256:<64hex> (repeatable)")
	fs.Var(&memoryRefs, "memory-ref", "logical memory/corpus reference (repeatable)")
	fs.Var(&secretRefs, "secret-ref", "logical secret reference such as secret:erp-readonly; contents are not inspected (repeatable)")
	fs.Var(&labels, "label", "untrusted source context label (repeatable; never promoted into policy labels)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 1 {
		return errors.New("usage: meshmcp air handoff offer [flags] <peer-ip:port>")
	}
	if *targetKey == "" || *workRaw == "" || *goal == "" {
		return errors.New("air handoff offer: --target-key, --work, and --goal are required")
	}
	if *networkTimeout <= 0 {
		return errors.New("air handoff offer: --timeout must be greater than zero")
	}
	work, err := parseHandoffWork(*workRaw)
	if err != nil {
		return fmt.Errorf("air handoff offer: %w", err)
	}

	var cursor json.RawMessage
	if *cursorPath != "" {
		var r io.Reader
		var closeCursor func() error
		if *cursorPath == "-" {
			r = os.Stdin
		} else {
			f, err := os.Open(*cursorPath)
			if err != nil {
				return fmt.Errorf("air handoff offer: open cursor: %w", err)
			}
			r, closeCursor = f, f.Close
		}
		cursor, err = readHandoffCursor(r)
		if closeCursor != nil {
			_ = closeCursor()
		}
		if err != nil {
			return fmt.Errorf("air handoff offer: %w", err)
		}
	}

	refs := make([]air.BlobRef, 0, len(artifacts))
	for _, raw := range artifacts {
		ref, err := parseHandoffArtifact(raw)
		if err != nil {
			return fmt.Errorf("air handoff offer: %w", err)
		}
		refs = append(refs, ref)
	}
	handoffID := *id
	if handoffID == "" {
		handoffID, err = air.NewHandoffID()
		if err != nil {
			return err
		}
	}
	now := time.Now().UTC()
	key := strings.TrimPrefix(*targetKey, "pubkey:")
	capsule := air.ContextCapsule{
		Version: air.HandoffVersion, ID: handoffID, CreatedAt: now, ExpiresAt: now.Add(*ttl),
		TargetKey: key, Work: work, Goal: *goal, Summary: *summary, Cursor: cursor,
		Artifacts: refs, MemoryRefs: []string(memoryRefs), SecretRefs: []string(secretRefs),
		Labels: []string(labels), Sensitivity: *sensitivity,
	}
	offer, err := air.SealHandoff(capsule)
	if err != nil {
		return fmt.Errorf("air handoff offer: %w", err)
	}
	if err := offer.Validate(now, key); err != nil {
		return fmt.Errorf("air handoff offer: %w", err)
	}

	o.BlockInbound = true
	client, err := startMesh(o, os.Stderr)
	if err != nil {
		return err
	}
	defer stopMesh(client)
	if err := verifyHandoffTargetIdentity(client, fs.Arg(0), offer.Capsule.TargetKey); err != nil {
		return fmt.Errorf("air handoff offer: %w", err)
	}
	signalCtx, stop := signal.NotifyContext(context.Background(), shutdownSignals...)
	defer stop()
	sendCtx, cancel := context.WithTimeout(signalCtx, *networkTimeout)
	defer cancel()
	if err := sendHandoffOffer(sendCtx, client, fs.Arg(0), offer); err != nil {
		return fmt.Errorf("air handoff offer: %w", err)
	}
	if *asJSON {
		return printHandoffJSON(offer)
	}
	fmt.Println(okLine("offered %s → %s", offer.Capsule.ID, fs.Arg(0)) + dim("  "+offer.ContentHash))
	return nil
}

func verifyHandoffTargetIdentity(client *embed.Client, addr, expectedKey string) error {
	return verifyHandoffTargetAddress(addr, expectedKey, func(ip netip.Addr) (string, error) {
		pubKey, _, ok := client.IdentityForIP(ip)
		if !ok {
			return "", errors.New("mesh identity is unavailable for destination IP")
		}
		return pubKey, nil
	})
}

func verifyHandoffTargetAddress(addr, expectedKey string, identityForIP func(netip.Addr) (string, error)) error {
	host, _, err := net.SplitHostPort(addr)
	if err != nil {
		return fmt.Errorf("invalid destination address: %w", err)
	}
	ip, err := netip.ParseAddr(host)
	if err != nil {
		return errors.New("destination must use a mesh IP literal so its transport identity can be verified before context is sent")
	}
	actualKey, err := identityForIP(ip)
	if err != nil {
		return fmt.Errorf("resolve destination mesh identity: %w", err)
	}
	if actualKey == "" || actualKey != expectedKey {
		return errors.New("destination mesh identity does not match the expected exact key; no context was sent")
	}
	return nil
}

func sendHandoffOffer(ctx context.Context, client *embed.Client, addr string, offer air.HandoffOffer) error {
	baseDial := func(ctx context.Context) (net.Conn, error) { return client.Dial(ctx, "tcp", addr) }
	dial := exactPeerDial(baseDial, offer.Capsule.TargetKey, func(addr net.Addr) string {
		pubKey, _ := peerIdentity(client, addr)
		return pubKey
	}, "connected peer identity does not match handoff target key")
	return sendHandoffOfferWithDial(ctx, dial, offer)
}

// sendSteerEnvelopeToPeer pins every (re)connection to the exact destination
// agent identity. Handoff context is sensitive even after local acceptance, so
// an address alone is not an adequate continuation target.
func sendSteerEnvelopeToPeer(ctx context.Context, client *embed.Client, addr, expectedKey string, env steerEnvelope) error {
	baseDial := func(ctx context.Context) (net.Conn, error) { return client.Dial(ctx, "tcp", addr) }
	dial := exactPeerDial(baseDial, expectedKey, func(addr net.Addr) string {
		pubKey, _ := peerIdentity(client, addr)
		return pubKey
	}, "connected peer identity does not match --agent-key")
	return sendSteerEnvelopeWithDial(ctx, dial, env)
}

func exactPeerDial(base session.Dialer, expectedKey string, keyForAddr func(net.Addr) string, mismatch string) session.Dialer {
	return func(ctx context.Context) (net.Conn, error) {
		conn, err := base(ctx)
		if err != nil {
			return nil, err
		}
		actualKey := ""
		if keyForAddr != nil {
			actualKey = keyForAddr(conn.RemoteAddr())
		}
		if actualKey == "" || actualKey != expectedKey {
			_ = conn.Close()
			return nil, errors.New(mismatch)
		}
		return conn, nil
	}
}

func sendHandoffOfferWithDial(ctx context.Context, dial session.Dialer, offer air.HandoffOffer) error {
	if ctx == nil {
		return errors.New("air handoff offer requires a context")
	}
	if !time.Now().Before(offer.Capsule.ExpiresAt) {
		return errors.New("air handoff offer has expired")
	}
	var outgoing bytes.Buffer
	if err := air.WriteHandoff(&outgoing, offer); err != nil {
		return err
	}
	stream := newHandoffOfferStream(outgoing.Bytes())
	defer stream.Close()
	expiryCtx, cancel := context.WithDeadline(ctx, offer.Capsule.ExpiresAt)
	defer cancel()
	if err := session.NewClient(dial, log.Printf).Run(expiryCtx, stream); err != nil {
		return err
	}
	ack, err := stream.acknowledgement()
	if err != nil {
		return err
	}
	if err := ack.ValidateFor(offer); err != nil {
		return err
	}
	if !ack.Accepted() {
		return fmt.Errorf("destination rejected handoff offer (%s)", ack.Reason)
	}
	return nil
}

// handoffOfferStream keeps the send half open after its one offer frame until
// an application ACK arrives. Session transport CLOSE alone is not acceptance.
type handoffOfferStream struct {
	outgoing *bytes.Reader

	mu      sync.Mutex
	ack     bytes.Buffer
	ackDone chan struct{}
	once    sync.Once
}

func newHandoffOfferStream(outgoing []byte) *handoffOfferStream {
	return &handoffOfferStream{outgoing: bytes.NewReader(outgoing), ackDone: make(chan struct{})}
}

func (s *handoffOfferStream) Read(p []byte) (int, error) {
	if n, err := s.outgoing.Read(p); n > 0 || err != io.EOF {
		return n, err
	}
	<-s.ackDone
	return 0, io.EOF
}

func (s *handoffOfferStream) Write(p []byte) (int, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.ack.Len()+len(p) > air.HandoffMaxAckBytes+1 {
		return 0, errors.New("handoff acknowledgement exceeds the wire limit")
	}
	n, err := s.ack.Write(p)
	if bytes.IndexByte(s.ack.Bytes(), '\n') >= 0 {
		s.once.Do(func() { close(s.ackDone) })
	}
	return n, err
}

func (s *handoffOfferStream) Close() error {
	s.once.Do(func() { close(s.ackDone) })
	return nil
}

func (s *handoffOfferStream) acknowledgement() (air.HandoffAck, error) {
	s.mu.Lock()
	b := append([]byte(nil), s.ack.Bytes()...)
	s.mu.Unlock()
	return air.ReadHandoffAck(bytes.NewReader(b))
}

func cmdAirHandoffReceive(args []string) error {
	fs := flag.NewFlagSet("air handoff receive", flag.ExitOnError)
	o := meshFlags(fs)
	port := fs.Int("port", 9140, "mesh port to receive handoff offers on")
	inboxDir := fs.String("inbox", "", "private durable handoff inbox directory (required)")
	auditPath := fs.String("audit", "", "hash-chained receipt file (default: <inbox>/handoff-audit.jsonl)")
	maxRecords := fs.Int("max-inbox", defaultHandoffInboxLimit, "maximum durable offers; records are never silently evicted")
	rate := fs.Float64("rate", 12, "maximum offers per verified source identity per minute")
	allow := multiFlag{}
	fs.Var(&allow, "allow", "source identity allowed to offer handoffs (FQDN glob or pubkey:<key>); repeatable; REQUIRED")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 || *inboxDir == "" {
		return errors.New("usage: meshmcp air handoff receive --inbox <dir> --allow <identity> [flags]")
	}
	if len(allow) == 0 {
		return errors.New("air handoff receive: at least one --allow is required (deny-by-default)")
	}
	inbox, err := newHandoffInbox(*inboxDir, *maxRecords)
	if err != nil {
		return err
	}
	path := *auditPath
	if path == "" {
		path = filepath.Join(inbox.dir, "handoff-audit.jsonl")
	}
	auditOwner, err := acquireHandoffPathLock(path+".receiver.lock", defaultHandoffLockTimeout)
	if err != nil {
		return fmt.Errorf("air handoff receive: this audit path already has an active receiver: %w", err)
	}
	defer auditOwner.release()
	audit, closeAudit, err := openHandoffAudit(path)
	if err != nil {
		return fmt.Errorf("air handoff receive: audit: %w", err)
	}
	defer closeAudit()

	o.BlockInbound = false
	client, err := startMesh(o, os.Stderr)
	if err != nil {
		return err
	}
	defer stopMesh(client)
	status, err := client.Status()
	if err != nil {
		return fmt.Errorf("air handoff receive: mesh status: %w", err)
	}
	localKey := status.LocalPeerState.PubKey
	if localKey == "" {
		return errors.New("air handoff receive: local mesh identity has no public key")
	}
	ln, err := client.ListenTCP(fmt.Sprintf(":%d", *port))
	if err != nil {
		return fmt.Errorf("air handoff receive: listen on mesh port %d: %w", *port, err)
	}
	defer ln.Close()

	ctx, stop := signal.NotifyContext(context.Background(), shutdownSignals...)
	defer stop()
	go func() { <-ctx.Done(); _ = ln.Close() }()

	checker := newACL(allow)
	limiter := newRingLimiter(*rate)
	deniedAuditLimiter := newRingLimiter(1)
	factory := newHandoffReceiveFactory(inbox, localKey, limiter, audit, time.Now)
	srv := session.NewServer(factory, 2*time.Minute, log.Printf)
	fmt.Fprintln(os.Stderr, dim("handoff inbox ")+bold(inbox.dir)+dim(fmt.Sprintf(" · mesh port %d · Ctrl-C to stop", *port)))
	fmt.Fprintln(os.Stderr, dim("target key ")+localKey)
	for {
		conn, err := ln.Accept()
		if err != nil {
			if ctx.Err() != nil {
				return nil
			}
			return fmt.Errorf("air handoff receive: accept: %w", err)
		}
		pubKey, fqdn := peerIdentity(client, conn.RemoteAddr())
		meta := session.Meta{PeerFQDN: fqdn, PeerAddr: conn.RemoteAddr().String(), PeerKey: pubKey}
		if !checker.allows(pubKey, fqdn) {
			key := pubKey
			if key == "" {
				key = conn.RemoteAddr().String()
			}
			if deniedAuditLimiter.allow(key, time.Now()) {
				_ = appendHandoffAudit(audit, meta, air.HandoffOffer{}, "deny", "source identity is not allowed")
			}
			conn.Close()
			continue
		}
		go srv.Handle(conn, meta)
	}
}

// newHandoffReceiveFactory returns a send-only session backend. It validates,
// rate-limits, and stores offers as inert state; it never launches, steers, or
// calls a tool. Source attribution comes exclusively from session.Meta.
func newHandoffReceiveFactory(inbox *handoffInbox, localTargetKey string, limiter *ringLimiter, audit *policy.AuditLog, nowf func() time.Time) session.BackendFactory {
	if nowf == nil {
		nowf = time.Now
	}
	deniedAuditLimiter := newRingLimiter(1)
	return func(meta session.Meta) (session.Backend, error) {
		pr, pw := io.Pipe()
		d := &handoffAckSink{pw: pw, done: make(chan struct{}), closed: make(chan struct{})}
		go func() {
			ack := receiveHandoffOffer(pr, inbox, localTargetKey, limiter, deniedAuditLimiter, audit, meta, nowf)
			_ = pr.Close()
			d.finish(ack)
		}()
		return d, nil
	}
}

func receiveHandoffOffer(r io.Reader, inbox *handoffInbox, localTargetKey string, limiter, deniedAuditLimiter *ringLimiter, audit *policy.AuditLog, meta session.Meta, nowf func() time.Time) air.HandoffAck {
	rejected := func(reason string) air.HandoffAck {
		return air.HandoffAck{Version: air.HandoffVersion, Status: air.HandoffAckRejected, Reason: reason}
	}
	key := meta.PeerKey
	if key == "" {
		key = meta.PeerFQDN
	}
	limitNow := nowf().UTC()
	if limiter != nil && !limiter.allow(key, limitNow) {
		if deniedAuditLimiter == nil || deniedAuditLimiter.allow(key, limitNow) {
			if err := appendHandoffAudit(audit, meta, air.HandoffOffer{}, "deny", "source identity rate-limited"); err != nil {
				return rejected("receipt_unavailable")
			}
		}
		return rejected("rate_limited")
	}
	offer, err := air.ReadHandoff(r)
	if err != nil {
		_ = appendHandoffAudit(audit, meta, air.HandoffOffer{}, "deny", "invalid handoff framing")
		return rejected("invalid_offer")
	}
	// ReadHandoff can block while a source dribbles the frame. Validate and
	// timestamp the receipt against a fresh clock after the complete line is in
	// hand so a pre-expiry connection cannot smuggle an expired capsule.
	receivedAt := nowf().UTC()
	rec, created, err := inbox.Put(offer, meta, localTargetKey, receivedAt)
	if err != nil {
		if auditErr := appendHandoffAudit(audit, meta, offer, "deny", "handoff offer rejected"); auditErr != nil {
			return rejected("receipt_unavailable")
		}
		return rejected("offer_rejected")
	}
	reason := "handoff offer stored"
	status := air.HandoffAckStored
	if !created {
		reason = "idempotent handoff replay suppressed"
		status = air.HandoffAckReplayed
	}
	if err := appendHandoffAudit(audit, meta, rec.Offer, "allow", reason); err != nil {
		return rejected("receipt_unconfirmed")
	}
	log.Printf("handoff %s from %s stored (state=%s)", rec.Offer.Capsule.ID, meta.PeerFQDN, rec.State)
	return air.HandoffAck{Version: air.HandoffVersion, ID: rec.Offer.Capsule.ID, ContentHash: rec.Offer.ContentHash, Status: status}
}

// handoffAckSink is a single-offer duplex session backend. Writes feed the
// bounded parser; Read blocks until validation/storage/audit produce an ACK.
type handoffAckSink struct {
	pw        *io.PipeWriter
	done      chan struct{}
	closed    chan struct{}
	closeOnce sync.Once
	ack       []byte
	off       int
}

func (d *handoffAckSink) Write(p []byte) (int, error) { return d.pw.Write(p) }

func (d *handoffAckSink) Read(p []byte) (int, error) {
	<-d.done
	if d.off >= len(d.ack) {
		// Keep the server output pump alive after it queues the ACK. The
		// client closes only after its local writer has consumed the newline;
		// returning EOF here could race CLOSE ahead of that writer.
		<-d.closed
		return 0, io.EOF
	}
	n := copy(p, d.ack[d.off:])
	d.off += n
	return n, nil
}

func (d *handoffAckSink) Close() error {
	_ = d.pw.Close()
	<-d.done
	d.closeOnce.Do(func() { close(d.closed) })
	return nil
}

func (d *handoffAckSink) finish(ack air.HandoffAck) {
	var wire bytes.Buffer
	if err := air.WriteHandoffAck(&wire, ack); err != nil {
		wire.Reset()
		_ = air.WriteHandoffAck(&wire, air.HandoffAck{Version: air.HandoffVersion, Status: air.HandoffAckRejected, Reason: "internal_error"})
	}
	d.ack = wire.Bytes()
	close(d.done)
}

func appendHandoffAudit(audit *policy.AuditLog, meta session.Meta, offer air.HandoffOffer, decision, reason string) error {
	if audit == nil {
		return nil
	}
	rec := policy.AuditRecord{
		Backend: "handoff", Peer: meta.PeerFQDN, PeerKey: meta.PeerKey, PeerAddr: meta.PeerAddr,
		Method: "air/handoff/offer", Decision: decision, Reason: reason, Rule: -1,
	}
	if id, err := canonicalHandoffID(offer.Capsule.ID); err == nil {
		rec.RPCID = id
	}
	if decision == "allow" && strings.HasPrefix(offer.ContentHash, "sha256:") {
		rec.Provenance = []string{offer.ContentHash}
	}
	return audit.Append(rec)
}

func openHandoffAudit(path string) (*policy.AuditLog, func(), error) {
	var before os.FileInfo
	if info, err := os.Lstat(path); err == nil {
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			return nil, nil, errors.New("handoff audit path is not a regular file")
		}
		before = info
	} else if !os.IsNotExist(err) {
		return nil, nil, err
	}
	seq, last, err := seedAuditFromExisting(path)
	if err != nil {
		return nil, nil, err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		return nil, nil, err
	}
	opened, err := f.Stat()
	if err != nil || !opened.Mode().IsRegular() {
		f.Close()
		return nil, nil, errors.New("opened handoff audit is not a regular file")
	}
	if before == nil && opened.Size() != 0 {
		f.Close()
		return nil, nil, errors.New("handoff audit path appeared with content while opening")
	}
	current, err := os.Lstat(path)
	if err != nil || current.Mode()&os.ModeSymlink != 0 || !current.Mode().IsRegular() || !os.SameFile(current, opened) || (before != nil && !os.SameFile(before, opened)) {
		f.Close()
		return nil, nil, errors.New("handoff audit path changed while opening")
	}
	if err := f.Chmod(0o600); err != nil {
		f.Close()
		return nil, nil, fmt.Errorf("secure handoff audit: %w", err)
	}
	log := policy.NewAuditLog(f, nowRFC3339).WithFailClosed(true)
	log.SeedFrom(seq, last)
	return log, func() { _ = f.Close() }, nil
}

func cmdAirHandoffList(args []string) error {
	fs := flag.NewFlagSet("air handoff list", flag.ExitOnError)
	inboxDir := fs.String("inbox", "", "handoff inbox directory (required)")
	asJSON := fs.Bool("json", false, "print records as JSON (includes capsule context)")
	state := fs.String("state", "", "filter by effective state")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 || *inboxDir == "" {
		return errors.New("usage: meshmcp air handoff list --inbox <dir> [--state <state>] [--json]")
	}
	if *state != "" && !validHandoffStateFilter(*state) {
		return fmt.Errorf("air handoff list: unknown state %q (want offered | accepted | dispatching | declined | continued | expired)", *state)
	}
	inbox, err := newHandoffInbox(*inboxDir)
	if err != nil {
		return err
	}
	records, err := inbox.List()
	if err != nil {
		return err
	}
	now := time.Now().UTC()
	filtered := records[:0]
	for i := range records {
		if *state == "" || string(records[i].EffectiveState(now)) == *state {
			filtered = append(filtered, records[i])
		}
	}
	if *asJSON {
		views := make([]handoffRecordView, 0, len(filtered))
		for _, rec := range filtered {
			views = append(views, newHandoffRecordView(rec, now))
		}
		return printHandoffJSON(views)
	}
	if len(filtered) == 0 {
		fmt.Println(dim("no handoff offers"))
		return nil
	}
	rows := make([][]cell, 0, len(filtered))
	for _, rec := range filtered {
		rows = append(rows, []cell{
			styled(string(rec.EffectiveState(now)), handoffStateStyle(rec.EffectiveState(now))),
			styled(rec.Offer.Capsule.ID, cyan),
			plain(rec.SourcePeer),
			plain(string(rec.Offer.Capsule.Work.Kind) + ":" + rec.Offer.Capsule.Work.ID),
			plain(handoffListGoal(rec)),
		})
	}
	renderTable(os.Stdout, []string{"state", "id", "source", "work", "goal"}, rows)
	return nil
}

func handoffStateStyle(state air.HandoffState) func(string) string {
	switch state {
	case air.HandoffAccepted, air.HandoffDispatching:
		return amber
	case air.HandoffContinued:
		return green
	case air.HandoffDeclined, air.HandoffExpired:
		return dim
	default:
		return cyan
	}
}

func cmdAirHandoffShow(args []string) error {
	fs := flag.NewFlagSet("air handoff show", flag.ExitOnError)
	inboxDir := fs.String("inbox", "", "handoff inbox directory (required)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 1 || *inboxDir == "" {
		return errors.New("usage: meshmcp air handoff show --inbox <dir> <id>")
	}
	inbox, err := newHandoffInbox(*inboxDir)
	if err != nil {
		return err
	}
	rec, found, err := inbox.Get(fs.Arg(0))
	if err != nil {
		return err
	}
	if !found {
		return errHandoffNotFound
	}
	return printHandoffJSON(newHandoffRecordView(rec, time.Now().UTC()))
}

func cmdAirHandoffTransition(args []string, next air.HandoffState) error {
	action := string(next)
	switch next {
	case air.HandoffAccepted:
		action = "accept"
	case air.HandoffDeclined:
		action = "decline"
	}
	fs := flag.NewFlagSet("air handoff "+action, flag.ExitOnError)
	inboxDir := fs.String("inbox", "", "handoff inbox directory (required)")
	note := fs.String("note", "", "bounded local decision note (never sent to the source)")
	asJSON := fs.Bool("json", false, "print the updated record as JSON")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 1 || *inboxDir == "" {
		return fmt.Errorf("usage: meshmcp air handoff %s --inbox <dir> <id>", action)
	}
	inbox, err := newHandoffInbox(*inboxDir)
	if err != nil {
		return err
	}
	rec, err := inbox.Transition(fs.Arg(0), next, time.Now().UTC(), *note)
	if err != nil {
		return fmt.Errorf("air handoff %s: %w", action, err)
	}
	if *asJSON {
		return printHandoffJSON(rec)
	}
	fmt.Println(okLine("handoff %s %s", rec.Offer.Capsule.ID, rec.State))
	return nil
}

func cmdAirHandoffContinue(args []string) error {
	fs := flag.NewFlagSet("air handoff continue", flag.ExitOnError)
	o := meshFlags(fs)
	inboxDir := fs.String("inbox", "", "handoff inbox directory (required)")
	agentKeyFlag := fs.String("agent-key", "", "exact destination agent WireGuard public key (required; pubkey: prefix accepted)")
	tool := fs.String("tool", "", "destination tool selected by the receiver (required; never taken from capsule context)")
	networkTimeout := fs.Duration("timeout", 2*time.Minute, "maximum time to wait for the destination inbox application ACK")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 2 || *inboxDir == "" || *agentKeyFlag == "" || *tool == "" {
		return errors.New("usage: meshmcp air handoff continue --inbox <dir> --agent-key <key> --tool <name> <id> <agent-ip:port>")
	}
	if *networkTimeout <= 0 {
		return errors.New("air handoff continue: --timeout must be greater than zero")
	}
	inbox, err := newHandoffInbox(*inboxDir)
	if err != nil {
		return err
	}
	o.BlockInbound = true
	client, err := startMesh(o, os.Stderr)
	if err != nil {
		return err
	}
	defer stopMesh(client)
	agentKey := strings.TrimPrefix(*agentKeyFlag, "pubkey:")
	if strings.TrimSpace(agentKey) == "" || agentKey != strings.TrimSpace(agentKey) || len(agentKey) > 256 || handoffHasControl(agentKey) {
		return errors.New("air handoff continue: invalid --agent-key")
	}
	if err := verifyHandoffTargetIdentity(client, fs.Arg(1), agentKey); err != nil {
		return fmt.Errorf("air handoff continue: %w", err)
	}
	deliver := func(ctx context.Context, addr string, env steerEnvelope) error {
		return sendSteerEnvelopeToPeer(ctx, client, addr, agentKey, env)
	}
	signalCtx, stop := signal.NotifyContext(context.Background(), shutdownSignals...)
	defer stop()
	deliveryCtx, cancel := context.WithTimeout(signalCtx, *networkTimeout)
	defer cancel()
	rec, err := continueStoredHandoff(deliveryCtx, inbox, fs.Arg(0), fs.Arg(1), agentKey, *tool, time.Now, deliver)
	if err != nil {
		return fmt.Errorf("air handoff continue: %w", err)
	}
	fmt.Println(okLine("continuation delivered %s → %s", rec.Offer.Capsule.ID, fs.Arg(1)) + dim(" · execution remains policy-governed"))
	return nil
}

func cmdAirHandoffRearm(args []string) error {
	fs := flag.NewFlagSet("air handoff rearm", flag.ExitOnError)
	inboxDir := fs.String("inbox", "", "handoff inbox directory (required)")
	note := fs.String("note", "", "required record of the downstream receipt check")
	asJSON := fs.Bool("json", false, "print the updated record as JSON")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 1 || *inboxDir == "" || strings.TrimSpace(*note) == "" {
		return errors.New("usage: meshmcp air handoff rearm --inbox <dir> --note <receipt-check> <id>")
	}
	inbox, err := newHandoffInbox(*inboxDir)
	if err != nil {
		return err
	}
	rec, err := inbox.Rearm(fs.Arg(0), time.Now().UTC(), *note)
	if err != nil {
		return fmt.Errorf("air handoff rearm: %w", err)
	}
	if *asJSON {
		return printHandoffJSON(rec)
	}
	fmt.Println(okLine("handoff %s re-armed after explicit unknown-outcome check", rec.Offer.Capsule.ID))
	return nil
}

func cmdAirHandoffArchive(args []string) error {
	fs := flag.NewFlagSet("air handoff archive", flag.ExitOnError)
	inboxDir := fs.String("inbox", "", "handoff inbox directory (required)")
	olderThan := fs.Duration("older-than", 24*time.Hour, "minimum age of terminal or expired unknown-dispatch records")
	asJSON := fs.Bool("json", false, "print archived IDs as JSON")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 || *inboxDir == "" || *olderThan < 0 {
		return errors.New("usage: meshmcp air handoff archive --inbox <dir> [--older-than 24h]")
	}
	inbox, err := newHandoffInbox(*inboxDir)
	if err != nil {
		return err
	}
	ids, err := inbox.Archive(time.Now().UTC(), *olderThan)
	if err != nil {
		return fmt.Errorf("air handoff archive: %w", err)
	}
	if *asJSON {
		return printHandoffJSON(ids)
	}
	fmt.Println(okLine("archived %d retained handoff receipt(s) → %s", len(ids), inbox.archiveDir()))
	return nil
}

type handoffDeliver func(context.Context, string, steerEnvelope) error

func continueStoredHandoff(ctx context.Context, inbox *handoffInbox, id, agentAddr, agentKey, tool string, nowf func() time.Time, deliver handoffDeliver) (air.HandoffRecord, error) {
	if ctx == nil {
		return air.HandoffRecord{}, errors.New("handoff continuation requires a context")
	}
	if err := ctx.Err(); err != nil {
		return air.HandoffRecord{}, err
	}
	if strings.TrimSpace(agentAddr) == "" || agentAddr != strings.TrimSpace(agentAddr) || len(agentAddr) > 512 || handoffHasControl(agentAddr) {
		return air.HandoffRecord{}, errors.New("invalid destination agent address")
	}
	if strings.TrimSpace(agentKey) == "" || agentKey != strings.TrimSpace(agentKey) || len(agentKey) > 256 || handoffHasControl(agentKey) {
		return air.HandoffRecord{}, errors.New("invalid destination agent key")
	}
	if nowf == nil {
		return air.HandoffRecord{}, errors.New("handoff continuation requires a clock")
	}
	if deliver == nil {
		return air.HandoffRecord{}, errors.New("handoff continuation requires a delivery function")
	}
	rec, found, err := inbox.Get(id)
	if err != nil {
		return air.HandoffRecord{}, err
	}
	if !found {
		return air.HandoffRecord{}, errHandoffNotFound
	}
	checkNow := nowf().UTC()
	if checkNow.IsZero() {
		return air.HandoffRecord{}, errors.New("handoff continuation clock returned zero time")
	}
	if rec.EffectiveState(checkNow) != air.HandoffAccepted {
		if rec.EffectiveState(checkNow) == air.HandoffExpired {
			_, _ = inbox.Transition(id, air.HandoffExpired, checkNow, "offer expired")
		}
		return air.HandoffRecord{}, fmt.Errorf("handoff must be accepted and unexpired before continuation (state %s)", rec.EffectiveState(checkNow))
	}
	env, err := handoffContinuationEnvelope(rec, tool)
	if err != nil {
		return air.HandoffRecord{}, err
	}
	claimNow := nowf().UTC()
	if claimNow.IsZero() {
		return air.HandoffRecord{}, errors.New("handoff continuation clock returned zero time")
	}
	claimed, err := inbox.ClaimDelivery(id, agentAddr, agentKey, tool, claimNow)
	if err != nil {
		return air.HandoffRecord{}, fmt.Errorf("claim continuation delivery: %w", err)
	}
	// Use the capsule's absolute expiry as the authority. This covers time
	// spent in preflight, store locking, delivery, and application-ACK wait.
	deliveryCtx, cancel := context.WithDeadline(ctx, claimed.Offer.Capsule.ExpiresAt)
	err = deliver(deliveryCtx, agentAddr, env)
	ctxErr := deliveryCtx.Err()
	acknowledgedAt := nowf().UTC()
	cancel()
	if err != nil {
		return air.HandoffRecord{}, fmt.Errorf("continuation delivery outcome is unknown; handoff remains dispatching (inspect downstream receipts, then use handoff rearm): %w", err)
	}
	if ctxErr != nil {
		return air.HandoffRecord{}, fmt.Errorf("continuation delivery outcome is unknown; handoff remains dispatching (inspect downstream receipts, then use handoff rearm): %w", ctxErr)
	}
	if acknowledgedAt.IsZero() || !acknowledgedAt.Before(claimed.Offer.Capsule.ExpiresAt) {
		return air.HandoffRecord{}, errors.New("continuation reached its expiry boundary with an unknown delivery outcome; handoff remains dispatching")
	}
	// This means the steer was delivered, not that the destination tool
	// succeeded. The capsule ID correlates downstream receipts; the destination
	// must provide its own deduplication if a tool needs exactly-once semantics.
	continued, err := inbox.AcknowledgeDelivery(id, acknowledgedAt)
	if err != nil {
		return air.HandoffRecord{}, fmt.Errorf("destination acknowledged the continuation but its local receipt could not be committed; handoff remains dispatching with an unknown outcome: %w", err)
	}
	return continued, nil
}

func handoffContinuationEnvelope(rec air.HandoffRecord, tool string) (steerEnvelope, error) {
	if rec.State != air.HandoffAccepted {
		return steerEnvelope{}, fmt.Errorf("handoff state %s is not accepted", rec.State)
	}
	if strings.TrimSpace(tool) == "" || tool != strings.TrimSpace(tool) || len(tool) > 256 || handoffHasControl(tool) {
		return steerEnvelope{}, errors.New("destination tool must be explicitly selected")
	}
	payload := struct {
		Handoff struct {
			Capsule     air.ContextCapsule `json:"capsule"`
			ContentHash string             `json:"content_hash"`
			SourcePeer  string             `json:"source_peer"`
			SourceKey   string             `json:"source_key"`
		} `json:"handoff"`
		HandlingHints []string `json:"handling_hints"`
	}{}
	payload.Handoff.Capsule = rec.Offer.Capsule
	payload.Handoff.ContentHash = rec.Offer.ContentHash
	payload.Handoff.SourcePeer = rec.SourcePeer
	payload.Handoff.SourceKey = rec.SourceKey
	// Sender labels remain inside the capsule as untrusted source metadata.
	// These handling hints are explicit advisory data for the destination tool;
	// they are not policy.Filter taint labels and grant no authority.
	payload.HandlingHints = []string{"handoff", "untrusted-context", "handoff:" + rec.Offer.Capsule.Sensitivity}
	b, err := json.Marshal(payload)
	if err != nil {
		return steerEnvelope{}, err
	}
	env := air.Task(tool, b)
	env.ID = rec.Offer.Capsule.ID
	if err := env.Validate(); err != nil {
		return steerEnvelope{}, err
	}
	return env, nil
}

func parseHandoffWork(raw string) (air.WorkRef, error) {
	kindRaw, id, ok := strings.Cut(raw, ":")
	if !ok || strings.TrimSpace(id) == "" || id != strings.TrimSpace(id) || handoffHasControl(id) {
		return air.WorkRef{}, fmt.Errorf("bad --work %q (want agent|session|task|workflow:<id>)", sanitizeCell(raw))
	}
	kind := air.WorkKind(kindRaw)
	switch kind {
	case air.WorkAgent, air.WorkSession, air.WorkTask, air.WorkWorkflow:
	default:
		return air.WorkRef{}, fmt.Errorf("bad --work kind %q (groups cannot receive a target-key-bound handoff)", sanitizeCell(kindRaw))
	}
	return air.WorkRef{Kind: kind, ID: id}, nil
}

func parseHandoffArtifact(raw string) (air.BlobRef, error) {
	name, hash, ok := strings.Cut(raw, "=")
	if !ok || name == "" || name == "." || name == ".." || len(name) > 255 || strings.ContainsAny(name, `/\`) || handoffHasControl(name) {
		return air.BlobRef{}, fmt.Errorf("bad --artifact %q (want base-name=sha256:<64hex>)", sanitizeCell(raw))
	}
	if len(hash) != len("sha256:")+64 || !strings.HasPrefix(hash, "sha256:") {
		return air.BlobRef{}, fmt.Errorf("bad --artifact hash for %q", sanitizeCell(name))
	}
	for _, c := range hash[len("sha256:"):] {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return air.BlobRef{}, fmt.Errorf("bad --artifact hash for %q", sanitizeCell(name))
		}
	}
	return air.BlobRef{Name: name, SHA256: hash}, nil
}

func readHandoffCursor(r io.Reader) (json.RawMessage, error) {
	b, err := io.ReadAll(io.LimitReader(r, air.HandoffMaxInlineBytes+1))
	if err != nil {
		return nil, err
	}
	if len(b) == 0 {
		return nil, errors.New("handoff cursor is empty")
	}
	if len(b) > air.HandoffMaxInlineBytes {
		return nil, fmt.Errorf("handoff cursor exceeds %d bytes", air.HandoffMaxInlineBytes)
	}
	if !json.Valid(b) {
		return nil, errors.New("handoff cursor must be valid JSON")
	}
	return json.RawMessage(b), nil
}

func handoffHasControl(s string) bool {
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return true
		}
	}
	return false
}

func validHandoffStateFilter(state string) bool {
	switch air.HandoffState(state) {
	case air.HandoffOffered, air.HandoffAccepted, air.HandoffDispatching, air.HandoffDeclined, air.HandoffContinued, air.HandoffExpired:
		return true
	default:
		return false
	}
}

func handoffListGoal(rec air.HandoffRecord) string {
	switch rec.Offer.Capsule.Sensitivity {
	case air.SensitivitySensitive, air.SensitivityRestricted:
		return "[" + rec.Offer.Capsule.Sensitivity + " context — use show to inspect]"
	default:
		return oneLine(rec.Offer.Capsule.Goal)
	}
}

func printHandoffJSON(v any) error {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(b))
	return nil
}

type handoffRecordView struct {
	air.HandoffRecord
	EffectiveState air.HandoffState `json:"effective_state"`
}

func newHandoffRecordView(rec air.HandoffRecord, now time.Time) handoffRecordView {
	return handoffRecordView{HandoffRecord: rec, EffectiveState: rec.EffectiveState(now)}
}
