package air

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestDeviceNameFromHost(t *testing.T) {
	cases := map[string]string{
		"MyLaptop":       "meshmcp-mylaptop",
		"host.local":     "meshmcp-host-local",
		"  Spaces Here ": "meshmcp-spaces-here",
		"":               "meshmcp-gateway",
		"!!!":            "meshmcp-gateway",
		"a_b__c":         "meshmcp-a-b-c",
	}
	for in, want := range cases {
		if got := DeviceNameFromHost(in); got != want {
			t.Errorf("DeviceNameFromHost(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestParseBackendSpec_Stdio(t *testing.T) {
	got, err := ParseBackendSpec("kg=python -m my_server")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got.Name != "kg" {
		t.Errorf("name = %q, want kg", got.Name)
	}
	if got.HTTP != "" {
		t.Errorf("HTTP should be empty, got %q", got.HTTP)
	}
	want := []string{"python", "-m", "my_server"}
	if len(got.Stdio) != len(want) {
		t.Fatalf("stdio = %v, want %v", got.Stdio, want)
	}
	for i := range want {
		if got.Stdio[i] != want[i] {
			t.Errorf("stdio[%d] = %q, want %q", i, got.Stdio[i], want[i])
		}
	}
}

func TestParseBackendSpec_HTTP(t *testing.T) {
	for _, addr := range []string{"http://127.0.0.1:3001", "https://svc.local/mcp"} {
		got, err := ParseBackendSpec("web=" + addr)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got.HTTP != addr {
			t.Errorf("HTTP = %q, want %q", got.HTTP, addr)
		}
		if got.Stdio != nil {
			t.Errorf("stdio should be nil for http, got %v", got.Stdio)
		}
	}
}

func TestParseBackendSpec_Invalid(t *testing.T) {
	for _, spec := range []string{"noequals", "=cmd", "name=", "name=   ", "\x00bad=cmd"} {
		if _, err := ParseBackendSpec(spec); err == nil {
			t.Errorf("ParseBackendSpec(%q) should error", spec)
		}
	}
}

func TestPairAddressAndFQDN(t *testing.T) {
	if got := DeviceFQDN("gw"); got != "gw.netbird.cloud" {
		t.Errorf("DeviceFQDN = %q", got)
	}
	if got := PairAddress("gw", 9600); got != "gw.netbird.cloud:9600" {
		t.Errorf("PairAddress = %q", got)
	}
}

// TestRenderConfigYAML_PruneAndComment proves the renderer drops zero-value
// noise, keeps the meaningful deny-by-default posture, and frames the file —
// all without changing the schema (it round-trips back to the same map).
func TestRenderConfigYAML_PruneAndComment(t *testing.T) {
	// A marshaled-struct shape with the null/empty noise a struct marshal emits.
	marshaled := []byte(`mesh:
  device_name: gw
  setup_key: ""
  log_level: warn
trace: null
registry: ""
audit_fail_closed: false
audit_log: ./audit.jsonl
backends:
  - name: example
    port: 9101
    session_ttl_seconds: 0
    policy:
      default_allow: false
      rules: []
`)
	out, err := RenderConfigYAML(marshaled)
	if err != nil {
		t.Fatalf("RenderConfigYAML: %v", err)
	}
	s := string(out)

	// Prune assertions apply to the ACTIVE config, not the commented appendix
	// (which deliberately shows a `rules:` example).
	active := s
	if idx := strings.Index(s, "# ----"); idx >= 0 {
		active = s[:idx]
	}
	for _, noisy := range []string{"trace:", "registry:", "audit_fail_closed:", "setup_key:", "session_ttl_seconds:", "rules:"} {
		if strings.Contains(active, noisy) {
			t.Errorf("expected %q to be pruned, got:\n%s", noisy, active)
		}
	}
	// Meaningful values kept.
	for _, keep := range []string{"device_name: gw", "audit_log: ./audit.jsonl", "default_allow: false", "name: example"} {
		if !strings.Contains(s, keep) {
			t.Errorf("expected %q to be kept, got:\n%s", keep, s)
		}
	}
	// Framed and taught.
	if !strings.Contains(s, "generated by") {
		t.Errorf("missing header comment")
	}
	if !strings.Contains(s, "deny-by-default") {
		t.Errorf("missing deny-by-default teaching comment")
	}
	if !strings.Contains(s, "Advanced (commented examples") {
		t.Errorf("missing advanced appendix")
	}

	// Schema fidelity: the pruned document still parses as a mapping.
	var back map[string]any
	if err := yaml.Unmarshal(out, &back); err != nil {
		t.Fatalf("rendered config does not re-parse: %v", err)
	}
	if _, ok := back["backends"]; !ok {
		t.Errorf("backends missing after render")
	}
}
