package air

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// This file renders the generated gateway config: it takes the YAML produced by
// marshaling the REAL Config struct (so field names can never drift from the
// schema), prunes the zero-value noise that a struct marshal emits, attaches
// light teaching comments, and frames the file with a header and a commented
// "advanced" appendix. The active config stays a faithful, editable view of the
// real schema — that is the progressive-disclosure contract: the same file a
// user later hand-tunes.

// keepFalsy is the set of keys whose zero value is meaningful and must survive
// pruning. default_allow:false is the deny-by-default posture — the whole point
// of a safe scaffold — so it is shown even though it is the zero value.
var keepFalsy = map[string]bool{"default_allow": true}

// headComments attaches a short teaching comment above each top-level section.
var headComments = map[string]string{
	"mesh":      "Mesh membership. The setup key is read from $NB_SETUP_KEY at\nrun time and is never written to this file.",
	"audit_log": "Tamper-evident, hash-chained audit ledger (one chain for the whole\ngateway). Verify it: meshmcp audit verify ./audit.jsonl",
	"control":   "Air control endpoint — how peers reach this gateway to pair and\ndrive live work. Default-deny: only listed identities may list/steer.",
	"backends":  "Backends exposed on the mesh. Each is deny-by-default: no tool is\nreachable until you add an allow rule to its policy.",
}

// RenderConfigYAML turns marshaled Config YAML into the final, teaching,
// safe-by-default scaffold file. It prunes zero-value noise, comments the
// sections, and frames the document. It never adds or renames a field, so the
// result round-trips back into the same Config.
func RenderConfigYAML(marshaled []byte) ([]byte, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(marshaled, &doc); err != nil {
		return nil, fmt.Errorf("parse marshaled config: %w", err)
	}
	if len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, fmt.Errorf("marshaled config is not a mapping document")
	}
	top := doc.Content[0]
	pruneMapping(top)
	for i := 0; i+1 < len(top.Content); i += 2 {
		key := top.Content[i]
		if c, ok := headComments[key.Value]; ok {
			key.HeadComment = c
		}
		if key.Value == "backends" {
			annotateBackends(top.Content[i+1])
		}
	}

	var b strings.Builder
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return nil, fmt.Errorf("encode scaffold config: %w", err)
	}
	_ = enc.Close()

	return []byte(scaffoldHeader + b.String() + scaffoldAppendix), nil
}

// annotateBackends adds a deny-by-default line comment to each backend's
// default_allow so the firewall stance is legible where it is enforced.
func annotateBackends(seq *yaml.Node) {
	if seq.Kind != yaml.SequenceNode {
		return
	}
	for _, be := range seq.Content {
		if be.Kind != yaml.MappingNode {
			continue
		}
		for i := 0; i+1 < len(be.Content); i += 2 {
			if be.Content[i].Value != "policy" {
				continue
			}
			pol := be.Content[i+1]
			for j := 0; j+1 < len(pol.Content); j += 2 {
				if pol.Content[j].Value == "default_allow" {
					pol.Content[j].LineComment = "deny-by-default: nothing is callable until you add an allow rule"
				}
			}
		}
	}
}

// pruneMapping drops map entries whose value is a zero value that carries no
// meaning (null, "", false, 0, empty map, empty sequence), unless the key is in
// keepFalsy. It recurses into nested mappings and sequence elements. Because
// anything omitted decodes back to its zero value, pruning never changes the
// config's meaning — it only removes noise the struct marshal emitted.
func pruneMapping(m *yaml.Node) {
	if m.Kind != yaml.MappingNode {
		return
	}
	kept := make([]*yaml.Node, 0, len(m.Content))
	for i := 0; i+1 < len(m.Content); i += 2 {
		key, val := m.Content[i], m.Content[i+1]
		if val.Kind == yaml.MappingNode {
			pruneMapping(val)
		}
		if val.Kind == yaml.SequenceNode {
			for _, el := range val.Content {
				pruneMapping(el)
			}
		}
		if !keepFalsy[key.Value] && isEmptyNode(val) {
			continue
		}
		kept = append(kept, key, val)
	}
	m.Content = kept
}

// isEmptyNode reports whether a node is a zero value with no information.
func isEmptyNode(n *yaml.Node) bool {
	switch n.Kind {
	case yaml.MappingNode, yaml.SequenceNode:
		return len(n.Content) == 0
	case yaml.ScalarNode:
		switch n.Tag {
		case "!!null":
			return true
		case "!!str":
			return n.Value == ""
		case "!!bool":
			return n.Value == "false"
		case "!!int":
			return n.Value == "0"
		}
	}
	return false
}

const scaffoldHeader = `# meshmcp gateway — generated by ` + "`air init`" + `.
#
# This file IS the advanced view: a real, editable meshmcp config. Everything
# here was chosen to be safe by default — deny-by-default policy, audit on — so
# you can go from nothing to a running, safe gateway with ` + "`air up`" + `.
#
# The one secret you must supply is the mesh setup key, from the environment:
#   export NB_SETUP_KEY=...    # from your NetBird dashboard
#   air up
#
# Hand-tune anything below; re-run ` + "`air up`" + ` to serve it.

`

const scaffoldAppendix = `
# ---------------------------------------------------------------------------
# Advanced (commented examples — uncomment and adapt as you grow):
#
# Grant a peer read-only access to a backend (progressive disclosure — add
# rules to open holes in the deny-by-default firewall):
#
#   policy:
#     default_allow: false
#     rules:
#       - peers: ["laptop-*.netbird.cloud"]   # who
#         tools: ["read_*", "search_*"]       # may call which tools
#         allow: true
#
# A Streamable-HTTP backend on localhost, reverse-proxied onto the mesh:
#
#   - name: local-http
#     port: 9102
#     http: http://127.0.0.1:3001
#
# See examples/agent-firewall.yaml for rate limits, time windows, taint
# tracking, and human co-sign.
`
